/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElRate: typeof import('element-plus/es')['ElRate']
    HeaderImage: typeof import('./src/components/header-image.vue')['default']
    NavigationBar: typeof import('./src/components/navigation-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
